### ISSUE TITLE
Ello <3

### ISSUE THREAD

**Issue by ghost** [AmbitiousSam/sqli-scanner#2]
Its missing alot of vulns urls that are 100% vuln  :'(

**Comment by AmbitiousSam** [comment]
Hey, this is a very basic scanner and I have not implemented anything advanced.
If you have any suggestions or improvements, you are free to pull a request.

**Comment by ghost** [comment]
My apologize i found the Problem i run wrong txt file though it thinkingi t was vuln list but it was before i scanned !

after finding that out i switched the file and it caught same amount of Vulns that where in the file 

sorry for wasting your time by being Dumb!!!! and not double checking things before i made an issue :/
you can close this and again im sorry that was my bad

**Comment by AmbitiousSam** [comment]
Hey, I am glad you were able to find some vulns using my tool.
No issues happen with me all the time.
Cheers && Happy Hunting
